language: ruby
rvm:
  - 2.0.0
  - 1.9.3
before_script:
  - cp config/database.example.yml config/database.yml
  - psql -c 'create database sidewalks_test;' -U postgres
  - rake db:migrate
bundler_args: --without development